sonar.projectKey=Tugamer89_FCG
sonar.organization=tugamer89

sonar.sources=.
sonar.exclusions=**/gl.h

sonar.cpd.exclusions=**/*
sonar.coverage.exclusions=**/*

sonar.cfamily.compile-commands=build/compile_commands.json